apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: statuspost

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: statuspost
  app.kubernetes.io/managed-by: kustomize

images:
  - name: statuspost
    newName: ghcr.io/arolang/example-statuspost
    newTag: latest
